### PR TITLE
Docker File Generated.

### PR DESCRIPTION
**Pull request by ShireenAzad**

### CODE REVIEW

**Comment by subbu-everest** [comment]
Use proper title for the PRs

**Comment by subbu-everest** [comment]
This PR have 20 changed files. Ideally, I should only have 2 files right? Can you check why?

**Comment by ShireenAzad** [comment]
> Use proper title for the PRs

Okay Bro.

**Comment by ShireenAzad** [comment]
> This PR have 20 changed files. Ideally, I should only have 2 files right? Can you check why?

Added the project along with docker. I will delete it.

**Pull request closed without merging**
